import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  HTTP_METHODS,
  MANAGED_OAS_FILE,
  OAS_SOURCE_KINDS,
  countOasEndpoints,
  describeOasSource,
  diffOperations,
  canonicalOasHash,
  stableStringify,
  isManagedSpec,
  normalizeApiPath,
  oasSourceForPick,
  operationSet,
} from '../lib/oas-source.js';

describe('oasSourceForPick', () => {
  // The bug this replaced: generate-oas hardcoded `{kind:'ai'}` at the
  // finalize call, so "use the spec we found" and "generate it with Fastify"
  // both persisted as if our model had written the file. A re-run then told
  // the user their hand-written spec was "generated with AI", and any
  // kind-based behaviour in `update` would have inherited that lie.
  it('records the spec already in the repo as found, with its path', () => {
    expect(oasSourceForPick('found', { existingOasFile: 'docs/openapi.yaml' })).toEqual({
      kind: 'found',
      path: 'docs/openapi.yaml',
    });
  });

  it('records framework generation as native, with the framework', () => {
    expect(oasSourceForPick('native', { framework: 'Fastify' })).toEqual({
      kind: 'native',
      framework: 'Fastify',
    });
  });

  it('records our own generation as ai', () => {
    expect(oasSourceForPick('ai', { framework: 'Fastify' })).toEqual({ kind: 'ai' });
  });

  it('never conflates found or native with ai', () => {
    const found = oasSourceForPick('found', { existingOasFile: 'a.json' });
    const native = oasSourceForPick('native', { framework: 'NestJS' });
    expect(found.kind).not.toBe('ai');
    expect(native.kind).not.toBe('ai');
  });

  it('returns null for picks that record their own provenance elsewhere', () => {
    // 'adopt' hands off to adoptExistingOas, which writes url/file/describe.
    expect(oasSourceForPick('adopt')).toBeNull();
  });

  it('tolerates a missing framework or path rather than writing undefined', () => {
    expect(oasSourceForPick('native', {})).toEqual({ kind: 'native', framework: null });
    expect(oasSourceForPick('found', {})).toEqual({ kind: 'found', path: null });
  });
});

describe('describeOasSource', () => {
  it('has a phrasing for every kind the CLI writes', () => {
    // The two halves have to stay in step: a kind with no phrasing here falls
    // through to "from your last setup", which is what `found` and `native`
    // used to do.
    for (const kind of OAS_SOURCE_KINDS) {
      expect(describeOasSource({ kind })).not.toBe('from your last setup');
    }
  });

  it('names the source concretely when it can', () => {
    expect(describeOasSource({ kind: 'url', url: 'https://a.com/o.json' })).toBe(
      'fetched from https://a.com/o.json',
    );
    expect(describeOasSource({ kind: 'file', input: 'docs/o.yaml' })).toBe('from docs/o.yaml');
    expect(describeOasSource({ kind: 'found', path: 'api/o.json' })).toBe(
      'already in your repo at api/o.json',
    );
    expect(describeOasSource({ kind: 'native', framework: 'tsoa' })).toBe('generated by tsoa');
  });

  it('never renders the recorded summary, however short it looks', () => {
    // `summary` is model-written prose kept so we can reproduce the spec. In
    // practice it runs to a paragraph about build internals, and every caller
    // of this renders exactly one line - a picker hint, a step header, a
    // status line. So it stays in the settings file.
    const long =
      'generated by running buildOpenApiSpec() from src/lib/api/openapiSpec.ts ' +
      '(the code behind the dynamic /api/v1/openapi.yaml endpoint) via tsx, ' +
      'with server URL https://app.restless.ai';
    expect(describeOasSource({ kind: 'describe', summary: long })).toBe(
      'from the location you described',
    );
    expect(describeOasSource({ kind: 'describe', summary: 'ran npm run openapi' })).toBe(
      'from the location you described',
    );
  });

  it('keeps every phrasing short enough for a one-line hint', () => {
    // The picker counts exactly one row per item, so a wrapped hint desyncs
    // its redraw math.
    for (const src of [
      { kind: 'describe', summary: 'x'.repeat(400) },
      { kind: 'url', url: `https://a.com/${'p'.repeat(200)}` },
      { kind: 'file', input: 'y'.repeat(300) },
      { kind: 'found', path: 'z'.repeat(300) },
    ]) {
      // A path or URL the developer chose is theirs and worth showing; only
      // the generated prose is capped. Guard the one we control.
      if (src.kind === 'describe') expect(describeOasSource(src).length).toBeLessThan(60);
    }
  });

  it('degrades to a generic phrasing when the detail is missing', () => {
    expect(describeOasSource({ kind: 'url' })).toBe('fetched from a URL');
    expect(describeOasSource({ kind: 'native' })).toBe('generated by your framework');
  });

  it('handles an absent or unknown source', () => {
    expect(describeOasSource(null)).toBe('from your last setup');
    expect(describeOasSource({ kind: 'wat' })).toBe('from your last setup');
  });
});

describe('isManagedSpec', () => {
  // Regenerating must never overwrite a spec the user maintains. A file we
  // wrote into .restless/ is ours; anything else is theirs, and a regenerate
  // writes to MANAGED_OAS_FILE and re-points the entry instead.
  it('recognizes the specs we generate', () => {
    expect(isManagedSpec(MANAGED_OAS_FILE)).toBe(true);
    expect(isManagedSpec('.restless/openapi.yaml')).toBe(true);
  });

  it('treats the user’s own files as off limits', () => {
    expect(isManagedSpec('docs/openapi.yaml')).toBe(false);
    expect(isManagedSpec('openapi.json')).toBe(false);
    expect(isManagedSpec('packages/api/spec.yaml')).toBe(false);
  });

  it('is not fooled by a path that merely mentions .restless', () => {
    expect(isManagedSpec('vendor/.restless-backup/openapi.json')).toBe(false);
    expect(isManagedSpec(null)).toBe(false);
  });
});

describe('normalizeApiPath', () => {
  it('collapses parameter names so a rename is not a diff', () => {
    expect(normalizeApiPath('/users/{id}')).toBe(normalizeApiPath('/users/{userId}'));
    expect(normalizeApiPath('/users/:id')).toBe(normalizeApiPath('/users/{id}'));
  });

  it('drops a trailing slash', () => {
    expect(normalizeApiPath('/pets/')).toBe('/pets');
  });

  it('keeps the root path addressable', () => {
    expect(normalizeApiPath('/')).toBe('/');
  });
});

describe('operationSet', () => {
  const OAS = {
    paths: {
      '/pets': {
        parameters: [{ name: 'limit' }],
        get: {},
        post: {},
      },
      '/pets/{id}': { get: {}, delete: {} },
    },
  };

  it('lists method+path pairs and ignores path-level keys', () => {
    expect([...operationSet(OAS)].sort()).toEqual([
      'DELETE /pets/{}',
      'GET /pets',
      'GET /pets/{}',
      'POST /pets',
    ]);
  });

  it('survives a malformed spec', () => {
    expect(operationSet(null).size).toBe(0);
    expect(operationSet({ paths: { '/x': null } }).size).toBe(0);
  });

  it('covers every method the spec parser recognizes', () => {
    const paths = {};
    for (const m of HTTP_METHODS) paths[`/${m}`] = { [m]: {} };
    expect(operationSet({ paths }).size).toBe(HTTP_METHODS.size);
  });
});

describe('diffOperations', () => {
  const before = { paths: { '/pets': { get: {} }, '/gone': { get: {} } } };
  const after = { paths: { '/pets': { get: {}, post: {} }, '/new': { get: {} } } };

  it('reports added and removed operations', () => {
    const d = diffOperations(before, after);
    expect(d.added).toEqual(['GET /new', 'POST /pets']);
    expect(d.removed).toEqual(['GET /gone']);
    expect(d.changed).toBe(true);
  });

  it('reports no change for an identical spec', () => {
    expect(diffOperations(before, before)).toEqual({
      added: [], removed: [], modified: [], changedSections: [], changed: false, metadataOnly: true,
    });
  });

  it('names the endpoints whose contents changed', () => {
    // The case behind "the spec changed, but the same endpoints are in it": a
    // regenerated spec with the same operations and different descriptions.
    // Reporting only added/removed made that message true and useless.
    const withDocs = {
      paths: { '/pets': { get: { summary: 'List pets', description: 'new prose' } }, '/gone': { get: {} } },
    };
    const d = diffOperations(before, withDocs);
    expect(d.added).toEqual([]);
    expect(d.removed).toEqual([]);
    expect(d.modified).toEqual(['GET /pets']);
    // `changed` stays "did the endpoint surface move" - the removal warning
    // and the coverage checks key off it.
    expect(d.changed).toBe(false);
    expect(d.metadataOnly).toBe(false);
  });

  it('reports metadataOnly when nothing inside any operation differs', () => {
    // Bytes differ (a new servers URL, a bumped version) but every operation
    // is identical, so there is nothing endpoint-shaped to show.
    const a = { servers: [{ url: 'https://a.com' }], paths: { '/pets': { get: {} } } };
    const b = { servers: [{ url: 'https://b.com' }], paths: { '/pets': { get: {} } } };
    const d = diffOperations(a, b);
    expect(d.modified).toEqual([]);
    expect(d.metadataOnly).toBe(true);
    // Naming the section is the whole answer for this case: without it the
    // report can only say "something outside your endpoints changed", which
    // makes the reader go and diff the file themselves.
    expect(d.changedSections).toEqual(['servers']);
  });

  it('names info when only the title changed', () => {
    // The real case that prompted this: a regenerated spec whose only
    // difference from the one on disk was info.title, 11 canonical bytes.
    const a = { info: { title: 'Restless', version: '1.0.0' }, paths: { '/p': { get: {} } } };
    const b = { info: { title: 'Restless Public API', version: '1.0.0' }, paths: { '/p': { get: {} } } };
    const d = diffOperations(a, b);
    expect(d.changedSections).toEqual(['info']);
    expect(d.metadataOnly).toBe(true);
  });

  it('reports no changed sections when only formatting differs', () => {
    // Indentation is not content. The file this came from differed by 560 raw
    // bytes and 11 canonical ones.
    const a = { info: { title: 'X' }, paths: { '/p': { get: { a: 1, b: 2 } } } };
    const b = { paths: { '/p': { get: { b: 2, a: 1 } } }, info: { title: 'X' } };
    expect(diffOperations(a, b).changedSections).toEqual([]);
  });

  it('does not treat key reordering as a change', () => {
    // A generator is free to emit keys in any order; JSON has no key order, so
    // a canonical comparison keeps that out of the report.
    const a = { paths: { '/pets': { get: { summary: 's', tags: ['x'], responses: {} } } } };
    const b = { paths: { '/pets': { get: { responses: {}, summary: 's', tags: ['x'] } } } };
    expect(diffOperations(a, b).modified).toEqual([]);
  });

  it('does treat array reordering as a change, since order is meaning there', () => {
    const a = { paths: { '/pets': { get: { tags: ['a', 'b'] } } } };
    const b = { paths: { '/pets': { get: { tags: ['b', 'a'] } } } };
    expect(diffOperations(a, b).modified).toEqual(['GET /pets']);
  });

  it('reports added, removed and revised together', () => {
    const a = { paths: { '/pets': { get: { summary: 'old' } }, '/gone': { get: {} } } };
    const b = { paths: { '/pets': { get: { summary: 'new' } }, '/new': { get: {} } } };
    const d = diffOperations(a, b);
    expect(d.added).toEqual(['GET /new']);
    expect(d.removed).toEqual(['GET /gone']);
    expect(d.modified).toEqual(['GET /pets']);
    expect(d.changed).toBe(true);
  });

  it('does not report a parameter rename as a change', () => {
    const a = { paths: { '/u/{id}': { get: {} } } };
    const b = { paths: { '/u/{userId}': { get: {} } } };
    expect(diffOperations(a, b).changed).toBe(false);
  });
});

describe('countOasEndpoints distinguishes empty from unreadable', () => {
  let tmp;
  beforeEach(() => { tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'count-oas-')); });
  afterEach(() => { fs.rmSync(tmp, { recursive: true, force: true }); });

  const write = (name, body) => {
    const p = path.join(tmp, name);
    fs.writeFileSync(p, body);
    return p;
  };

  it('returns null for a file that does not parse', () => {
    // loadOas returns null instead of throwing, so this used to count as 0
    // operations - indistinguishable from a valid spec with no paths. Three
    // callers treat null as "can't read it", so the difference is load-bearing.
    expect(countOasEndpoints(write('bad.json', '{{{ not json'))).toBeNull();
  });

  it('returns null for a missing file', () => {
    expect(countOasEndpoints(path.join(tmp, 'nope.json'))).toBeNull();
  });

  it('returns 0 for a spec that genuinely has no operations', () => {
    expect(countOasEndpoints(write('empty.json', '{"openapi":"3.0.0","paths":{}}'))).toBe(0);
  });

  it('counts operations in a real spec', () => {
    const body = '{"openapi":"3.0.0","paths":{"/a":{"get":{},"post":{}},"/b":{"get":{}}}}';
    expect(countOasEndpoints(write('ok.json', body))).toBe(3);
  });
});

/**
 * The cross-repo contract.
 *
 * `canonicalOasHash` is compared against a value the DASHBOARD computes with
 * its own copy of the same algorithm (`src/lib/oasSync.ts`), to decide whether
 * its spec matches this one. Two implementations in two repos, so nothing but a
 * shared fixture keeps them honest. The dashboard pins the SAME expected hash
 * in `src/lib/oasSync.test.ts`; if you change the canonicalization, both must
 * change together or `update` will report the dashboard as permanently out of
 * date.
 */
const CONTRACT_FIXTURE = {
  openapi: '3.0.0',
  info: { version: '1.0.0', title: 'Pets' },
  paths: {
    '/pets/{id}': { get: { responses: {}, summary: 'Get' } },
    '/pets': { post: { responses: {} }, get: { tags: ['a', 'b'], responses: {} } },
  },
};
const CONTRACT_HASH = '49a31f7c0c7f55ce03d5badd37f41e10e97ebd55593c94f7a3d6f5d89916fa59';

describe('canonicalOasHash (shared with the dashboard)', () => {
  it('matches the hash the dashboard pins for the same fixture', () => {
    expect(canonicalOasHash(CONTRACT_FIXTURE)).toBe(CONTRACT_HASH);
  });

  it('sorts keys at every level', () => {
    expect(stableStringify({ b: 1, a: { d: 2, c: 3 } })).toBe('{"a":{"c":3,"d":2},"b":1}');
  });

  it('ignores key order, so a reformat is not a change worth pushing', () => {
    expect(canonicalOasHash({ a: 1, b: 2 })).toBe(canonicalOasHash({ b: 2, a: 1 }));
  });

  it('does not ignore array order, where order is meaning', () => {
    expect(canonicalOasHash({ a: [1, 2] })).not.toBe(canonicalOasHash({ a: [2, 1] }));
  });

  it('returns null for a spec that is not there', () => {
    expect(canonicalOasHash(null)).toBeNull();
    expect(canonicalOasHash('nope')).toBeNull();
  });
});
