import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { runAI, loadPrompt } from '../lib/ai.js';
import { bold, dim, green, red } from '../lib/ui.js';
import { parseOas } from '../lib/oas-parse.js';
import { loadOas } from '../lib/oas-auth.js';
import { safeWriteFileSync, safeMkdirSync } from '../lib/pathGuard.js';

/**
 * Where a spec comes from, and how to get it again.
 *
 * `npx api init` records provenance on each API entry as `oasSource`, and
 * `npx api update` is the reason that matters: "refresh my spec" means
 * something completely different depending on how the spec got here. A URL
 * gets re-fetched (no AI, no code reading). A file the user maintains gets
 * re-read and re-validated, because it is already the source of truth and
 * nothing of ours should regenerate it. Only the AI and native-generator
 * kinds involve looking at the routes again.
 *
 * These primitives live here rather than in `steps/generate-oas.js` so both
 * flows share one implementation - otherwise the update path would grow a
 * second, subtly different copy of "fetch a spec and check it parses".
 */

/** Every `oasSource.kind` the CLI writes. */
export const OAS_SOURCE_KINDS = [
  'ai', // our model read the routes and wrote it
  'native', // the framework's own generator emitted it
  'found', // it was already in the repo; we point at it and never write it
  'file', // the user pointed us at a path
  'url', // fetched from a URL
  'describe', // located by AI from a plain-English description
  'agent', // written by a coding agent via `npx api register`
];

/**
 * The one path we own and are allowed to overwrite. A spec that came from the
 * user (`found` / `file`) lives wherever they keep it, and regenerating must
 * never clobber that - it writes here instead and re-points `oasFile`.
 */
export const MANAGED_OAS_FILE = '.restless/openapi.json';

export const HTTP_METHODS = new Set([
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace',
]);

/** Is this spec one we generated into `.restless/`, or the user's own file? */
export function isManagedSpec(oasFile) {
  if (!oasFile) return false;
  return !path.relative('.restless', oasFile).startsWith('..');
}

/**
 * Human-readable account of how a spec was sourced, for the reuse-on-rerun
 * note and for `update`'s per-kind action labels.
 */
export function describeOasSource(src) {
  switch (src?.kind) {
    case 'ai': return 'generated with AI';
    case 'native': return src.framework ? `generated by ${src.framework}` : 'generated by your framework';
    case 'found': return src.path ? `already in your repo at ${src.path}` : 'already in your repo';
    case 'url': return src.url ? `fetched from ${src.url}` : 'fetched from a URL';
    case 'file': return src.input ? `from ${src.input}` : 'from a file you provided';
    // Deliberately NOT `src.summary`. That is model-written prose recorded so we
    // can reproduce the spec later, and it runs to whole paragraphs describing
    // internals ("generated by running buildOpenApiSpec() from src/lib/... via
    // tsx, with server URL ..."). Every caller of this renders one short line -
    // a picker hint, a step header, a status line - so the summary belongs in
    // the settings file, not on screen.
    case 'describe': return 'from the location you described';
    case 'agent': return 'written by your coding agent';
    default: return 'from your last setup';
  }
}

/**
 * Which `oasSource` a source-picker choice should record. Kept next to
 * `describeOasSource` so the two can't drift: every kind this can produce
 * needs a phrasing there.
 */
export function oasSourceForPick(picked, { existingOasFile, framework } = {}) {
  switch (picked) {
    case 'found': return { kind: 'found', path: existingOasFile || null };
    case 'native': return { kind: 'native', framework: framework || null };
    case 'ai': return { kind: 'ai' };
    default: return null;
  }
}

// Collapse a path to a shape we can compare across sources: parameter names
// don't matter for coverage (`/users/{id}` == `/users/{userId}` == `/users/:id`),
// and a trailing slash is not a distinct route.
export function normalizeApiPath(p) {
  const collapsed = p
    .replace(/\{[^}]+\}/g, '{}') // {id} / {userId} -> {}
    .replace(/:[^/]+/g, '{}') // :id -> {}
    .replace(/\/+$/, ''); // drop trailing slash
  return collapsed === '' ? '/' : collapsed;
}

/**
 * Every operation in a parsed spec, as `METHOD /normalized/path` strings.
 * Normalizing the path means a rename of `{id}` to `{userId}` doesn't read as
 * "one route removed, one added" in a diff.
 */
export function operationSet(oas) {
  const out = new Set();
  for (const [p, ops] of Object.entries(oas?.paths || {})) {
    if (!ops || typeof ops !== 'object') continue;
    for (const m of Object.keys(ops)) {
      if (HTTP_METHODS.has(m.toLowerCase())) {
        out.add(`${m.toUpperCase()} ${normalizeApiPath(p)}`);
      }
    }
  }
  return out;
}

/** Key order is not meaning in JSON, so compare a canonical form. Otherwise a
 *  generator that emits keys in a different order reads as a change.
 *
 *  MIRRORED in the dashboard at `src/lib/oasSync.ts`. The two implementations
 *  must produce identical output byte for byte, because `oasHash` is compared
 *  across the wire to decide whether the dashboard's spec matches the local
 *  one. Both repos pin it with the same fixture hash. */
export function stableStringify(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  const keys = Object.keys(value).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(value[k])}`).join(',')}}`;
}

/** Every operation as `METHOD /normalized/path` -> canonical body. */
function operationBodies(oas) {
  const out = new Map();
  for (const [p, ops] of Object.entries(oas?.paths || {})) {
    if (!ops || typeof ops !== 'object') continue;
    for (const [m, op] of Object.entries(ops)) {
      if (!HTTP_METHODS.has(m.toLowerCase())) continue;
      out.set(`${m.toUpperCase()} ${normalizeApiPath(p)}`, stableStringify(op));
    }
  }
  return out;
}

/**
 * What changed between two parsed specs, at the level someone can act on.
 *
 * Added and removed endpoints are the headline. But a regenerated spec very
 * often has exactly the same endpoints with different descriptions, schemas or
 * examples - which matters, because those are what the docs and the AI chat
 * actually serve. Reporting only added/removed left the honest-but-useless
 * "the spec changed, but the same endpoints are in it", so `modified` counts
 * the shared operations whose contents differ, and `metadataOnly` says the
 * difference was entirely outside the operations (servers, info, components).
 */
export function diffOperations(beforeOas, afterOas) {
  const before = operationBodies(beforeOas);
  const after = operationBodies(afterOas);
  const added = [...after.keys()].filter((op) => !before.has(op)).sort();
  const removed = [...before.keys()].filter((op) => !after.has(op)).sort();
  const modified = [...after.keys()]
    .filter((op) => before.has(op) && before.get(op) !== after.get(op))
    .sort();
  // Which top-level sections other than `paths` differ. Without this the
  // no-operation-changed case can only guess ("the server URL, version or
  // components moved"), when naming the section is both cheap and the whole
  // answer - a regenerated spec whose only difference is `info.title` should
  // say so.
  const sections = [...new Set([...Object.keys(beforeOas || {}), ...Object.keys(afterOas || {})])]
    .filter((k) => k !== 'paths')
    .filter((k) => stableStringify(beforeOas?.[k]) !== stableStringify(afterOas?.[k]))
    .sort();

  return {
    added,
    removed,
    modified,
    changedSections: sections,
    // `changed` stays "did the endpoint surface move", which is what the
    // removal warning and the coverage checks key off.
    changed: added.length > 0 || removed.length > 0,
    // Something differed, but not in any operation.
    metadataOnly: added.length === 0 && removed.length === 0 && modified.length === 0,
  };
}

/**
 * Count operations in a spec on disk, so a confirm screen can say "23
 * endpoints" - the fastest way for someone to tell whether a spec is the one
 * they meant. Returns null when the file won't parse.
 */
export function countOasEndpoints(absPath) {
  try {
    const oas = loadOas(absPath);
    // `loadOas` returns null rather than throwing on a parse failure, so
    // without this an unreadable spec counted as 0 operations instead of
    // "can't read it". Three callers key off null to mean exactly that:
    // `rememberedApis` drops such a spec rather than offering it, the
    // revalidate action reports it, and the up-front check fails soft.
    if (oas === null || typeof oas !== 'object') return null;
    let n = 0;
    for (const ops of Object.values(oas?.paths || {})) {
      for (const method of Object.keys(ops || {})) {
        if (HTTP_METHODS.has(method.toLowerCase())) n++;
      }
    }
    return n;
  } catch {
    return null;
  }
}

/**
 * Fingerprint of a spec's CONTENT, recorded when we push.
 *
 * Canonical, not byte-level, and that distinction is load-bearing twice over:
 *
 *  - Locally, it means reformatting a spec (a generator changing its
 *    indentation or key order) doesn't read as a change and doesn't prompt a
 *    pointless push. A real 560-byte reformat turned out to be 11 bytes of
 *    actual difference.
 *  - Across the wire, it makes the hash comparable at all. The dashboard
 *    parses an uploaded spec and stores the object, discarding the raw text,
 *    so it can never reproduce the bytes we hashed - but it can canonicalize
 *    the same way. That is how `update` can tell whether the dashboard's spec
 *    matches the local one without downloading it.
 *
 * A hash answers "did it change", not "what changed", which is why
 * `oasOperationCount` is stored alongside it and why the dashboard also hands
 * back its operation list.
 */
export function canonicalOasHash(oas) {
  if (!oas || typeof oas !== 'object') return null;
  return crypto.createHash('sha256').update(stableStringify(oas)).digest('hex');
}

/** Canonical hash of a spec on disk, or null if it won't parse. */
export function hashOasFile(absPath) {
  try {
    return canonicalOasHash(loadOas(absPath));
  } catch {
    return null;
  }
}

/** The fingerprint pair to record on an entry after a successful push. */
export function fingerprintSpec(absPath) {
  const oasHash = hashOasFile(absPath);
  if (!oasHash) return null;
  return { oasHash, oasOperationCount: countOasEndpoints(absPath) ?? 0 };
}

const MAX_OAS_FIX_ATTEMPTS = 2;

// Read the file we just wrote and parse it the same way the server will. If
// it doesn't parse, hand the error back to the LLM and ask it to fix the file
// in place. Retries up to MAX_OAS_FIX_ATTEMPTS times.
export async function validateAndFixOas({ oasFullPath, packageDir, setSpinner }) {
  for (let attempt = 0; attempt <= MAX_OAS_FIX_ATTEMPTS; attempt++) {
    let raw;
    try {
      raw = fs.readFileSync(oasFullPath, 'utf8');
    } catch (err) {
      return { ok: false, error: `Could not read ${oasFullPath}: ${err.message}` };
    }
    const format = oasFullPath.endsWith('.json') ? 'json' : 'yaml';
    const result = parseOas(raw, format);
    if (result.ok) return { ok: true };

    if (attempt === MAX_OAS_FIX_ATTEMPTS) {
      return { ok: false, error: result.error };
    }

    setSpinner('Fixing OpenAPI spec');
    const fixPrompt = loadPrompt('fix-oas', {
      oasFile: oasFullPath,
      parseError: result.error,
    });
    await runAI(fixPrompt, packageDir, { setSpinner });
  }
  return { ok: false, error: 'Exhausted fix attempts' };
}

export function isStrictJson(raw) {
  try {
    JSON.parse(raw);
    return true;
  } catch {
    return false;
  }
}

/**
 * Fetch a spec from a URL once, validate it parses (same parser the server
 * uses), and save it under .restless/. Returns the repo-relative path, or
 * null on any failure so the caller can re-prompt.
 *
 * `destBase` writes to `<destBase>.json` / `.yaml` instead of the canonical
 * `openapi.*`. `update` needs that: it re-fetches before asking permission, so
 * the download has to land somewhere disposable rather than on top of the spec
 * the user is still deciding whether to replace.
 */
export async function fetchOasFromUrl({ url, rootDir, apiDir, setSpinner, destBase = null }) {
  setSpinner({ phase: 'Fetching spec', detail: url });
  let raw;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      setSpinner('');
      console.log('');
      console.log(`  ${red('✗')} ${url} returned ${res.status}.`);
      return null;
    }
    raw = await res.text();
  } catch (err) {
    setSpinner('');
    console.log('');
    console.log(`  ${red('✗')} Couldn't fetch ${url}: ${err.message}`);
    return null;
  }
  setSpinner('');

  // Detect JSON vs YAML so we save with the right extension (validateAndFixOas
  // and the server both key off it). Try strict JSON first, then YAML.
  let format = 'json';
  let parsed = parseOas(raw, 'json');
  if (!parsed.ok || !isStrictJson(raw)) {
    const asYaml = parseOas(raw, 'yaml');
    if (asYaml.ok && !isStrictJson(raw)) {
      parsed = asYaml;
      format = 'yaml';
    }
  }
  if (!parsed.ok) {
    console.log('');
    console.log(`  ${red('✗')} That URL didn't return a valid OpenAPI spec.`);
    console.log(`  ${dim(parsed.error)}`);
    return null;
  }

  const ext = format === 'yaml' ? '.yaml' : '.json';
  const dest = destBase ? `${destBase}${ext}` : path.join(apiDir, `openapi${ext}`);
  // Make the destination's own directory, not `apiDir`: with `destBase` the
  // two differ, and a staging directory won't exist yet.
  const destDir = path.dirname(dest);
  if (!fs.existsSync(destDir)) safeMkdirSync(destDir, { recursive: true });
  safeWriteFileSync(dest, raw);
  const rel = path.relative(rootDir, dest);
  if (!destBase) {
    // Silent for a scratch download - "Downloaded to .oas-refresh.json" is an
    // implementation detail, and the caller reports the outcome that matters.
    console.log('');
    console.log(`  ${green('✓')} Downloaded to ${bold(rel)}.`);
  }
  return rel;
}

/**
 * Adopt an OAS file already on disk. Copies it into .restless/ if it lives
 * outside the repo (so it ships with the code), validates it parses, and
 * returns the repo-relative path, or null if it doesn't parse.
 */
export function adoptOasFile({ absPath, rootDir, apiDir }) {
  const raw = (() => {
    try { return fs.readFileSync(absPath, 'utf8'); } catch { return null; }
  })();
  if (raw === null) {
    console.log('');
    console.log(`  ${red('✗')} Couldn't read ${absPath}.`);
    return null;
  }
  const format = absPath.endsWith('.json') ? 'json' : 'yaml';
  const parsed = parseOas(raw, format);
  if (!parsed.ok) {
    console.log('');
    console.log(`  ${red('✗')} ${path.relative(rootDir, absPath)} didn't parse as an OpenAPI spec.`);
    console.log(`  ${dim(parsed.error)}`);
    return null;
  }

  const rel = path.relative(rootDir, absPath);
  if (rel.startsWith('..')) {
    // Outside the repo - copy into .restless/ so it lives with the codebase.
    if (!fs.existsSync(apiDir)) safeMkdirSync(apiDir, { recursive: true });
    const ext = path.extname(absPath) || '.yaml';
    const dest = path.join(apiDir, `openapi${ext}`);
    fs.copyFileSync(absPath, dest);
    const destRel = path.relative(rootDir, dest);
    console.log('');
    console.log(`  ${green('✓')} Copied to ${bold(destRel)} so it lives with your code.`);
    return destRel;
  }
  console.log('');
  console.log(`  ${green('✓')} Using the file at ${bold(rel)}.`);
  return rel;
}
